In [1]:
import numpy as np

In [2]:
a=np.random.randint(10,20,size=(10))
a

array([12, 10, 18, 12, 17, 18, 10, 15, 15, 16])

In [4]:
a=np.array(([1,2,3],[4,5,6],[7,8,10]))
b=np.array(([7,8,10],[4,5,6],[1,2,3]))
c=a+b
e=a-b
print(c)
print(e)

[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]


In [6]:
d=a@b
d

array([[ 18,  24,  31],
       [ 54,  69,  88],
       [ 91, 116, 148]])